/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author farhan
 */
public class PembayaranAdmin extends javax.swing.JFrame {
    private int selectedUserId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PembayaranAdmin.class.getName());
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    
    /**
     * Creates new form PembayaranAdmin
     */
    public PembayaranAdmin() {

    initComponents();
          
 
    koneksi();

    tampilData();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembayaranAdmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dropdownCari = new javax.swing.JComboBox<>();
        boxCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editNIM = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        editJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dropdownBulan = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnBukaBukti = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        Status = new javax.swing.JComboBox<>();
        Metode = new javax.swing.JComboBox<>();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 137, 211));

        jButton1.setBackground(new java.awt.Color(55, 137, 211));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mahasiswa");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(55, 137, 211));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Laporan");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(55, 137, 211));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Absensi");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(55, 137, 211));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tagihan");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(55, 137, 211));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pembayaran");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(55, 137, 211));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Pembayaran");

        tabelPembayaranAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Nim", "Bulan", "Jumlah", "Metode", "Status", "BuktiTranfer"
            }
        ));
        tabelPembayaranAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembayaranAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPembayaranAdmin);

        jLabel2.setText("Cari Data");

        dropdownCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "NIM" }));
        dropdownCari.addActionListener(this::dropdownCariActionPerformed);

        boxCari.addActionListener(this::boxCariActionPerformed);

        jLabel3.setText("ID");

        editID.addActionListener(this::editIDActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Edit Data");

        jLabel5.setText("Nama");

        editNama.addActionListener(this::editNamaActionPerformed);

        jLabel6.setText("Nim");

        editNIM.addActionListener(this::editNIMActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        jLabel7.setText("Bulan");

        editJumlah.addActionListener(this::editJumlahActionPerformed);

        jLabel8.setText("Jumlah");

        jLabel9.setText("Metode");

        dropdownBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        dropdownBulan.addActionListener(this::dropdownBulanBulanActionPerformed);

        jLabel12.setText("Status");

        btnBukaBukti.setText("Buka Bukti");
        btnBukaBukti.addActionListener(this::btnBukaBuktiActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Lunas", "Ditolak" }));
        Status.addActionListener(this::StatusBulanActionPerformed);

        Metode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Transfer" }));
        Metode.addActionListener(this::MetodeBulanActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(84, 84, 84)
                                        .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(dropdownBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Metode, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dropdownCari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(boxCari)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(513, 513, 513)
                                        .addComponent(btnHapus)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBukaBukti)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dropdownCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBukaBukti))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(Metode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(editNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dropdownBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSimpan)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new MahasiswaAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new LaporanAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose(); // tutup dashboard admin (opsional)   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new AbsensiMahasiswaAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TagihanAdmin().setVisible(true);

    this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         new PembayaranAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelPembayaranAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembayaranAdminMouseClicked
        // TODO add your handling code here:

       int baris = tabelPembayaranAdmin.getSelectedRow();

    editID.setText(
        tabelPembayaranAdmin.getValueAt(baris,0).toString());

    editNama.setText(
        tabelPembayaranAdmin.getValueAt(baris,1).toString());

    editNIM.setText(
        tabelPembayaranAdmin.getValueAt(baris,2).toString());

    dropdownBulan.setSelectedItem(
        tabelPembayaranAdmin.getValueAt(baris,3).toString());

    editJumlah.setText(
        tabelPembayaranAdmin.getValueAt(baris,4).toString());

    Metode.setSelectedItem(
        tabelPembayaranAdmin.getValueAt(baris,5).toString());

    Status.setSelectedItem(
        tabelPembayaranAdmin.getValueAt(baris,6).toString());
  
    }//GEN-LAST:event_tabelPembayaranAdminMouseClicked

    private void dropdownCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownCariActionPerformed

    private void boxCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCariActionPerformed

    editID.setText("");

    editNama.setText("");

    editNIM.setText("");

    editJumlah.setText("");

    
   

    dropdownBulan.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCariActionPerformed

    private void editIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIDActionPerformed

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void editNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNIMActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
            try {

        String sql = "UPDATE pembayaran SET "
                + "nama=?, nim=?, bulan=?, jumlah=?, metode=?, status=? "
                + "WHERE id=?";

        pst = con.prepareStatement(sql);

        pst.setString(1, editNama.getText());
        pst.setString(2, editNIM.getText());
        pst.setString(3, dropdownBulan.getSelectedItem().toString());
        pst.setString(4, editJumlah.getText());
        pst.setString(5, Metode.getSelectedItem().toString());
        pst.setString(6, Status.getSelectedItem().toString());
        pst.setString(7, editID.getText());

        pst.executeUpdate();
        
        if(Status.getSelectedItem().toString().equals("Lunas")){

    String hapusTagihan =
    "DELETE FROM tagihan WHERE nim=? AND bulan=?";

    PreparedStatement pst2 =
    con.prepareStatement(hapusTagihan);

    pst2.setString(1, editNIM.getText());
    pst2.setString(
        2,
        dropdownBulan.getSelectedItem().toString()
    );

    pst2.executeUpdate();
}

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil diupdate"
        );

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Nim");
    model.addColumn("Bulan");
    model.addColumn("Jumlah");
    model.addColumn("Metode");
    model.addColumn("Status");
    model.addColumn("BuktiTransfer");

    try {

        String pilihan =
        dropdownCari.getSelectedItem().toString();

        String kolom = "";

        if (pilihan.equalsIgnoreCase("Nama")) {
            kolom = "nama";
        } else if (pilihan.equalsIgnoreCase("NIM")
                || pilihan.equalsIgnoreCase("Nim")) {
            kolom = "nim";
        }

        String keyword =
        boxCari.getText();

        String sql =
        "SELECT * FROM pembayaran WHERE "
        + kolom +
        " LIKE ?";

        pst = con.prepareStatement(sql);

        pst.setString(1, "%" + keyword + "%");

        rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id"),
                rs.getString("nama"),
                rs.getString("nim"),
                rs.getString("bulan"),
                rs.getString("jumlah"),
                rs.getString("metode"),
                rs.getString("status"),
                rs.getString("bukti_transfer")

            });

        }

        tabelPembayaranAdmin.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
        null,
        e.getMessage());

    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void editJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJumlahActionPerformed

    private void dropdownBulanBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownBulanBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownBulanBulanActionPerformed

    private void btnBukaBuktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaBuktiActionPerformed
  try {

        int baris = tabelPembayaranAdmin.getSelectedRow();

        if (baris == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data terlebih dahulu"
            );

            return;
        }

        String path =
tabelPembayaranAdmin
.getValueAt(baris, 7)
.toString();

Desktop.getDesktop().open(
    new File(path)
);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
        null,
        e.getMessage());
    }
    }//GEN-LAST:event_btnBukaBuktiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {

        if (editID.getText().equals("")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data terlebih dahulu"
            );

            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
                null,
                "Yakin hapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {

            String sql =
            "DELETE FROM pembayaran WHERE id=?";

            pst = con.prepareStatement(sql);

            pst.setString(1, editID.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(
            null,
            "Data berhasil dihapus"
            );

            tampilData();

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
        null,
        e.getMessage()
        );
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void StatusBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusBulanActionPerformed

    private void MetodeBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetodeBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MetodeBulanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     new dashboardadmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

public void koneksi() {

    try {

        con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/gbq",
            "root",
            "admin123"
        );

        System.out.println("Koneksi berhasil");

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            null,
            "Koneksi gagal : " + e.getMessage()
        );

    }
}



public void tampilData() {

    DefaultTableModel model =
    new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Nim");
    model.addColumn("Bulan");
    model.addColumn("Jumlah");
    model.addColumn("Metode");
    model.addColumn("Status");
    model.addColumn("BuktiTransfer");

    try {

        String sql =
        "SELECT * FROM pembayaran";

        pst = con.prepareStatement(sql);

        rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id"),
                rs.getString("nama"),
                rs.getString("nim"),
                rs.getString("bulan"),
                rs.getString("jumlah"),
                rs.getString("metode"),
                rs.getString("status"),
                rs.getString("bukti_transfer")

            });

        }

        tabelPembayaranAdmin.setModel(model);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(0).setPreferredWidth(40);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(1).setPreferredWidth(120);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(2).setPreferredWidth(180);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(3).setPreferredWidth(180);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(4).setPreferredWidth(100);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(5).setPreferredWidth(100);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(6).setPreferredWidth(100);

        tabelPembayaranAdmin.getColumnModel()
        .getColumn(7).setPreferredWidth(200);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Gagal tampil data : " + e.getMessage()
        );

    }
}
public void clearForm() {

    editID.setText("");
    editNama.setText("");
    editNIM.setText("");
    editJumlah.setText("");

    dropdownBulan.setSelectedIndex(0);
    Metode.setSelectedIndex(0);
    Status.setSelectedIndex(0);
}

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PembayaranAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Metode;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField boxCari;
    private javax.swing.JButton btnBukaBukti;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> dropdownBulan;
    private javax.swing.JComboBox<String> dropdownCari;
    private javax.swing.JTextField editID;
    private javax.swing.JTextField editJumlah;
    private javax.swing.JTextField editNIM;
    private javax.swing.JTextField editNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPembayaranAdmin;
    // End of variables declaration//GEN-END:variables
}
