package view.admin;
        


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.text.DecimalFormat;
import view.admin.AbsensiMahasiswaAdmin;
import view.admin.MahasiswaAdmin;
import view.admin.PembayaranAdmin;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author farhan
 */
   public class TagihanAdmin extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(TagihanAdmin.class.getName());
    /**
     * Creates new form TagihanAdmin
     */
   public TagihanAdmin() {

    initComponents();

    try {

        con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/gbq",
            "root",
            "admin123"
        );

            tampilData();
            tampilMahasiswa();


    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
   
   public void tampilMahasiswa() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("NIM");

    tabelCariMahasiswa.setModel(model);

    try {

        String sql = "SELECT * FROM mahasiswa";

        pst = con.prepareStatement(sql);

        rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id"),
                rs.getString("nama"),
                rs.getString("nim")

            });

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}
   public void tampilData() {

    DefaultTableModel model = new DefaultTableModel();


    model.addColumn("Nama");
    model.addColumn("NIM");
    model.addColumn("Bulan");
    model.addColumn("Jumlah");
    model.addColumn("Status");

    tabelTagihanAdmin.setModel(model);

    try {

        String sql = "SELECT * FROM tagihan";

        pst = con.prepareStatement(sql);

        rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

             
                rs.getString("nama"),
                rs.getString("nim"),
                rs.getString("bulan"),
                new DecimalFormat("#,###").format(rs.getDouble("jumlah")),
                rs.getString("status")

            });

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTagihanAdmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dropdownCari = new javax.swing.JComboBox<>();
        boxCariTagihan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editNIM = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        editJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editStatus = new javax.swing.JComboBox<>();
        dropdownBulan = new javax.swing.JComboBox<>();
        btnCariTagihan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCariMahasiswa = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 137, 211));

        jButton1.setBackground(new java.awt.Color(55, 137, 211));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mahasiswa");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(55, 137, 211));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Laporan");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(55, 137, 211));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Absensi");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(55, 137, 211));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tagihan");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(55, 137, 211));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pembayaran");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(55, 137, 211));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Tagihan");

        tabelTagihanAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Nim", "Bulan", "Jumlah", "Status"
            }
        ));
        tabelTagihanAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTagihanAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTagihanAdmin);

        jLabel2.setText("Cari Data");

        dropdownCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "NIM" }));
        dropdownCari.addActionListener(this::dropdownCariActionPerformed);

        boxCariTagihan.addActionListener(this::boxCariTagihanActionPerformed);

        jLabel4.setText("Cari Mahasiswa");

        jLabel5.setText("Nama");

        editNama.addActionListener(this::editNamaActionPerformed);

        jLabel6.setText("Nim");

        editNIM.addActionListener(this::editNIMActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        jLabel7.setText("Bulan");

        editJumlah.addActionListener(this::editJumlahActionPerformed);

        jLabel8.setText("Jumlah");

        jLabel9.setText("Status");

        editStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));
        editStatus.addActionListener(this::editStatusBulanActionPerformed);

        dropdownBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        dropdownBulan.addActionListener(this::dropdownBulanBulanActionPerformed);

        btnCariTagihan.setText("Cari");
        btnCariTagihan.addActionListener(this::btnCariTagihanActionPerformed);

        tabelCariMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama ", "NIM"
            }
        ));
        tabelCariMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCariMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelCariMahasiswa);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapus)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dropdownCari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(boxCariTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCariTagihan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnSimpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnTambah))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(editJumlah)
                                                .addComponent(editStatus, 0, 163, Short.MAX_VALUE)
                                                .addComponent(dropdownBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(editNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dropdownCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCariTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariTagihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnTambah))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 new MahasiswaAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   new LaporanAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose(); // tutup dashboard admin (opsional)   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   new AbsensiMahasiswaAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          new TagihanAdmin().setVisible(true);

    this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   new PembayaranAdmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelTagihanAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTagihanAdminMouseClicked
        // TODO add your handling code here:

    int baris = tabelTagihanAdmin.getSelectedRow();

    editNama.setText(
        tabelTagihanAdmin.getValueAt(baris,0).toString());

    editNIM.setText(
        tabelTagihanAdmin.getValueAt(baris,1).toString());

    dropdownBulan.setSelectedItem(
        tabelTagihanAdmin.getValueAt(baris,2).toString());

    editJumlah.setText(
        tabelTagihanAdmin.getValueAt(baris,3).toString());

    editStatus.setSelectedItem(
        tabelTagihanAdmin.getValueAt(baris,4).toString());

    // TAMBAHAN
    nimLama = tabelTagihanAdmin.getValueAt(baris,1).toString();
    bulanLama = tabelTagihanAdmin.getValueAt(baris,2).toString();
  
    
    }//GEN-LAST:event_tabelTagihanAdminMouseClicked

    private void dropdownCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownCariActionPerformed

    private void boxCariTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCariTagihanActionPerformed

  

        editNama.setText("");

        editNIM.setText("");

        editJumlah.setText("");

 

        editStatus.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCariTagihanActionPerformed

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void editNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNIMActionPerformed
private String nimLama;
private String bulanLama;
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
  try {

        String sql = "UPDATE tagihan SET "
                + "nama=?, "
                + "nim=?, "
                + "bulan=?, "
                + "jumlah=?, "
                + "status=? "
                + "WHERE nim=? AND bulan=?";

        pst = con.prepareStatement(sql);

        // data baru
        pst.setString(1, editNama.getText());
        pst.setString(2, editNIM.getText());
        pst.setString(3, dropdownBulan.getSelectedItem().toString());
        pst.setString(4, editJumlah.getText());
        pst.setString(5, editStatus.getSelectedItem().toString());

        // data lama
        pst.setString(6, nimLama);
        pst.setString(7, bulanLama);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil diupdate");

        tampilData();

        editNama.setText("");
        editNIM.setText("");
        editJumlah.setText("");

        dropdownBulan.setSelectedIndex(0);
        editStatus.setSelectedIndex(0);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage());

    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
   try {

    String sql = "DELETE FROM tagihan WHERE nim=? AND bulan=?";

pst = con.prepareStatement(sql);

pst.setString(1, editNIM.getText());
pst.setString(2, dropdownBulan.getSelectedItem().toString());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(
            null,
            "Data berhasil dihapus");

    tampilData();

    editNama.setText("");
    editNIM.setText("");
    editJumlah.setText("");

    dropdownBulan.setSelectedIndex(0);
    editStatus.setSelectedIndex(0);

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            null,
            e.getMessage());

}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void editJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJumlahActionPerformed
        // TODO add your handling code here:
        try {

    String angka = editJumlah.getText().replace(",", "");

    double jumlah = Double.parseDouble(angka);

    DecimalFormat df = new DecimalFormat("#,###");

    editJumlah.setText(df.format(jumlah));

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, "Input harus angka");

}
    }//GEN-LAST:event_editJumlahActionPerformed

    private void editStatusBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStatusBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStatusBulanActionPerformed

    private void dropdownBulanBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownBulanBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownBulanBulanActionPerformed

    private void btnCariTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTagihanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =
new DefaultTableModel();

model.addColumn("Nama");
model.addColumn("Nim");
model.addColumn("Bulan");
model.addColumn("Jumlah");
model.addColumn("Status");

try {

    String kategori =
    dropdownCari.getSelectedItem().toString();

    String keyword =
    boxCariTagihan.getText();

    if(kategori.equals("Nama")){
        kategori = "nama";
    } else {
        kategori = "nim";
    }

    String sql =
    "SELECT * FROM tagihan WHERE "
    + kategori +
    " LIKE ?";

    pst = con.prepareStatement(sql);

    pst.setString(1, "%" + keyword + "%");

    rs = pst.executeQuery();

    while (rs.next()) {

        model.addRow(new Object[]{

            rs.getString("nama"),
            rs.getString("nim"),
            rs.getString("bulan"),
            rs.getString("jumlah"),
            rs.getString("status"),

        });

    }

    tabelTagihanAdmin.setModel(model);

} catch (Exception e) {

    JOptionPane.showMessageDialog(
        null,
        e.getMessage());

}
    }//GEN-LAST:event_btnCariTagihanActionPerformed

    private void tabelCariMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCariMahasiswaMouseClicked
        // TODO add your handling code here:
            int baris = tabelCariMahasiswa.getSelectedRow();

    editNama.setText(
        tabelCariMahasiswa.getValueAt(baris,1).toString());

    editNIM.setText(
        tabelCariMahasiswa.getValueAt(baris,2).toString());
    }//GEN-LAST:event_tabelCariMahasiswaMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
            try {

        String sql = "INSERT INTO tagihan "
                + "(nama,nim,bulan,jumlah,status) "
                + "VALUES (?,?,?,?,?)";

        pst = con.prepareStatement(sql);

        // hapus koma dulu
        String jumlahText = editJumlah.getText().replace(",", "");

        pst.setString(1, editNama.getText());
        pst.setString(2, editNIM.getText());
        pst.setString(3, dropdownBulan.getSelectedItem().toString());

        // simpan sebagai double
        pst.setDouble(4, Double.parseDouble(jumlahText));

        pst.setString(5, editStatus.getSelectedItem().toString());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil ditambahkan");

        tampilData();

        // reset form
        editNama.setText("");
        editNIM.setText("");
        editJumlah.setText("");

        dropdownBulan.setSelectedIndex(0);
        editStatus.setSelectedIndex(0);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage());

    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 new dashboardadmin().setVisible(true); // buka halaman mahasiswa
    this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TagihanAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxCariTagihan;
    private javax.swing.JButton btnCariTagihan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> dropdownBulan;
    private javax.swing.JComboBox<String> dropdownCari;
    private javax.swing.JTextField editJumlah;
    private javax.swing.JTextField editNIM;
    private javax.swing.JTextField editNama;
    private javax.swing.JComboBox<String> editStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelCariMahasiswa;
    private javax.swing.JTable tabelTagihanAdmin;
    // End of variables declaration//GEN-END:variables
}
