/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import view.guru.guru;
import view.mahasiswa.dashboardmahasiswa_1;
import view.admin.dashboardadmin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author LENOVO
 */
public class register extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(register.class.getName());

    /**
     * Creates new form register
     */
      public register() {
        initComponents();
        
          pilihRole.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Pilih Role", "Mahasiswa", "Guru", "Admin" }
    ));

        mahasiswa.setVisible(false);
        guru.setVisible(false);
        this.setLocationRelativeTo(null); // tengah layar
    }
    
  // RESET FORM
    public void hapusLayar() {
        txtEmail.setText("");
        txtUsername.setText("");
        txtPassword.setText("");

        pilihRole.setSelectedIndex(0);

        namaMahasiswa.setText("");
        guruNama.setText("");
        guruHp.setText("");

        mahasiswa.setVisible(false);
        guru.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        pilihRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        mahasiswa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nimMahasiswa1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        namaMahasiswa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        guru = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        guruNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        guruHp = new javax.swing.JTextField();

        jLabel2.setText("Username");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Guru", "Admin" }));
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel6.setText("Role");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Register");

        jLabel3.setText("Email");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        jLabel4.setText("Username");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        jLabel5.setText("Password");

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        pilihRole.setOpaque(true);
        pilihRole.addActionListener(this::pilihRoleActionPerformed);

        jLabel7.setText("Role");

        jLabel8.setText("NIM");

        nimMahasiswa1.addActionListener(this::nimMahasiswa1ActionPerformed);

        jLabel11.setText("Nama Mahasiwa");

        namaMahasiswa.addActionListener(this::namaMahasiswaActionPerformed);

        javax.swing.GroupLayout mahasiswaLayout = new javax.swing.GroupLayout(mahasiswa);
        mahasiswa.setLayout(mahasiswaLayout);
        mahasiswaLayout.setHorizontalGroup(
            mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mahasiswaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nimMahasiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        mahasiswaLayout.setVerticalGroup(
            mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mahasiswaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nimMahasiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel9.setText("Nama Lengkap");

        guruNama.addActionListener(this::guruNamaActionPerformed);

        jLabel10.setText("No Handphone");

        guruHp.addActionListener(this::guruHpActionPerformed);

        javax.swing.GroupLayout guruLayout = new javax.swing.GroupLayout(guru);
        guru.setLayout(guruLayout);
        guruLayout.setHorizontalGroup(
            guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guruLayout.createSequentialGroup()
                .addGroup(guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(guruLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(guruHp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guruLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guruNama, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        guruLayout.setVerticalGroup(
            guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guruLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(guruNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guruHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(pilihRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pilihRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void namaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMahasiswaActionPerformed

    private void guruNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guruNamaActionPerformed

    private void pilihRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihRoleActionPerformed
  String role = pilihRole.getSelectedItem().toString();

        mahasiswa.setVisible(false);
        guru.setVisible(false);

        if (role.equals("Mahasiswa")) {
            mahasiswa.setVisible(true);
        } else if (role.equals("Guru")) {
            guru.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pilihRoleActionPerformed

    private void guruHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guruHpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    String role = pilihRole.getSelectedItem().toString();


       try {
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String email = txtEmail.getText();
       

        String nim = nimMahasiswa1.getText();
        String namaMhs = namaMahasiswa.getText();

        // VALIDASI UMUM
        if (username.equals("") || password.equals("") || email.equals("")) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi!");
            return;
        }

        if (pilihRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih role dulu!");
            return;
        }

        // VALIDASI MAHASISWA
        if (role.equals("Mahasiswa") && (nim.equals("") || namaMhs.equals(""))) {
            JOptionPane.showMessageDialog(null, "NIM & Nama harus diisi!");
            return;
        }

        // VALIDASI GURU
        if (role.equals("Guru") && (guruNama.getText().equals("") || guruHp.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Nama & No HP harus diisi!");
            return;
        }

        Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost/gbq", "root", "admin123"
        );

        // INSERT LOGIN
        String sqlLogin = "INSERT INTO logingbq (nama, email, password, role, username) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sqlLogin, Statement.RETURN_GENERATED_KEYS);

        
String nama = "";

if (role.equals("Mahasiswa")) {
    nama = namaMahasiswa.getText();
} else if (role.equals("Guru")) {
    nama = guruNama.getText();
} else {
    nama = username; // untuk admin
}

pst.setString(1, nama);
pst.setString(2, email);
pst.setString(3, String.valueOf(password.hashCode()));
pst.setString(4, role);
pst.setString(5, username);

        pst.executeUpdate();

        ResultSet rs = pst.getGeneratedKeys();
        int userId = 0;

        if (rs.next()) {
            userId = rs.getInt(1);
        }

        if (userId == 0) {
            JOptionPane.showMessageDialog(null, "Gagal mendapatkan ID user!");
            return;
        }

        // MAHASISWA
        if (role.equals("Mahasiswa")) {
            String sqlMhs = "INSERT INTO mahasiswa (user_id, nim, nama) VALUES (?, ?, ?)";
            PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);

            pstMhs.setInt(1, userId);
            pstMhs.setString(2, nim);
            pstMhs.setString(3, namaMhs);

            pstMhs.executeUpdate();
        }

        // GURU
        if (role.equals("Guru")) {
            String sqlGuru = "INSERT INTO guru (user_id, nama, hp) VALUES (?, ?, ?)";
            PreparedStatement pstGuru = conn.prepareStatement(sqlGuru);

            pstGuru.setInt(1, userId);
            pstGuru.setString(2, guruNama.getText());
            pstGuru.setString(3, guruHp.getText());

            pstGuru.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
if (role.equals("Admin")) {

    new dashboardadmin().setVisible(true);

} else if (role.equals("Guru")) {

    new guru().setVisible(true);

} else {

    new dashboardmahasiswa_1(nim).setVisible(true);

}

this.dispose();
        

    } catch (Exception e) {
    e.printStackTrace(); // 🔥 WAJIB
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nimMahasiswa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimMahasiswa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimMahasiswa1ActionPerformed

public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new register().setVisible(true);
        }
    });
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel guru;
    private javax.swing.JTextField guruHp;
    private javax.swing.JTextField guruNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mahasiswa;
    private javax.swing.JTextField namaMahasiswa;
    private javax.swing.JTextField nimMahasiswa1;
    private javax.swing.JComboBox<String> pilihRole;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}